name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: corepack enable

      - name: Test
        run: pnpm test:types

      - name: Install
        run: pnpm i

      - name: Typecheck
        run: pnpm run test:types
